version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
    networks:
      - db-network
    volumes:
      - db-volume:/var/lib/mysql
  todoapp:
    image: todoapp:latest
    container_name: todoapp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.8
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=Development
      - PYTHONUNBUFFERED=1
    networks:
      - db-network
    depends_on:
      - mysql
    restart: always
    entrypoint: ["/entrypoint.sh"]
      
networks:
  db-network:
    driver: bridge

volumes:
  db-volume:
